server:
  port: 8888

oauth2:
  server:
    url: http://localhost:8080

security:
  oauth2:
    client:
      client-id: my-client
      client-secret: my-client-pass
    resource:
      jwt:
        key-value: jwt-secret

logging:
  level:
    org.springframework.security: DEBUG
