server:
  port: 9999


oauth2:
  server:
    url: http://localhost:8080
  resource:
    url: http://localhost:8888

security:
  oauth2:
    client:
      client-id: my-client
      client-secret: my-client-pass
      access-token-uri: ${oauth2.server.url}/uaa/oauth/token
      user-authorization-uri: ${oauth2.server.url}/uaa/oauth/authorize
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvJ5NOBuV4HDZT8+DCr5d
          3z1NSukDG5k8XZ8DQniqlttPTQPfkaecEDnEAdG3g2795xd4I0hzMPebUU0hqGVY
          C+jje4b5QKJBSmvvECdcABo4uthXlouiluBfny3Ka8AaVIh4UWnY7hKUKRpItIGc
          8OS8EzkUh9GS2OipikKx6ZFLlZj1AmRkzKpC8y+yFZ1giFklBz89nugt2brvcpx0
          AWMn8Xl+riR7OE5jugQ0UCcswYfp0EmlGBdvaJ05u+cES51se8mhsWZkTZh5mjQO
          XzA8swSrxUO/aSi3Dt0+i5Er2aq2PFMXcxLCPvxG7eL5cvjZBF/LXjr65uMC8Uy6
          NwIDAQAB
          -----END PUBLIC KEY-----


logging:
  level:
    org.springframework.security: DEBUG
